// Code generated by protoc-gen-go.
// source: squidbot.proto
// DO NOT EDIT!

package protocols

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// A message coming in from a frontend driver containing the sender's handle
type MessageRequest struct {
	// Used to help coordinate requests to replies.
	UniqueId int64 `protobuf:"varint,1,opt,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
	// Timestamp of the message as specified by the upstream service -- not the
	// frontend driver for squidbot.
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// The name of the sender who sent this message.
	SenderHandle string `protobuf:"bytes,3,opt,name=sender_handle,json=senderHandle" json:"sender_handle,omitempty"`
	// The body of the message.
	MessageBody string `protobuf:"bytes,4,opt,name=message_body,json=messageBody" json:"message_body,omitempty"`
	// The channel the message was sent in.
	ChannelName string `protobuf:"bytes,5,opt,name=channel_name,json=channelName" json:"channel_name,omitempty"`
	// Was this a 1:1 message?
	IsOneToOne bool `protobuf:"varint,6,opt,name=is_one_to_one,json=isOneToOne" json:"is_one_to_one,omitempty"`
}

func (m *MessageRequest) Reset()                    { *m = MessageRequest{} }
func (m *MessageRequest) String() string            { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()               {}
func (*MessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *MessageRequest) GetUniqueId() int64 {
	if m != nil {
		return m.UniqueId
	}
	return 0
}

func (m *MessageRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageRequest) GetSenderHandle() string {
	if m != nil {
		return m.SenderHandle
	}
	return ""
}

func (m *MessageRequest) GetMessageBody() string {
	if m != nil {
		return m.MessageBody
	}
	return ""
}

func (m *MessageRequest) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *MessageRequest) GetIsOneToOne() bool {
	if m != nil {
		return m.IsOneToOne
	}
	return false
}

type MessageResponse struct {
	// The id of the message sent from a frontend to the brain. Helps to
	// coordinate the responses to the reuqests.
	UniqueId int64 `protobuf:"varint,1,opt,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
	// The message containing the response.
	MessageBody string `protobuf:"bytes,2,opt,name=message_body,json=messageBody" json:"message_body,omitempty"`
}

func (m *MessageResponse) Reset()                    { *m = MessageResponse{} }
func (m *MessageResponse) String() string            { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()               {}
func (*MessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *MessageResponse) GetUniqueId() int64 {
	if m != nil {
		return m.UniqueId
	}
	return 0
}

func (m *MessageResponse) GetMessageBody() string {
	if m != nil {
		return m.MessageBody
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageRequest)(nil), "protocols.MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "protocols.MessageResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Brain service

type BrainClient interface {
	// Posts a message from a frontend
	OnNewMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type brainClient struct {
	cc *grpc.ClientConn
}

func NewBrainClient(cc *grpc.ClientConn) BrainClient {
	return &brainClient{cc}
}

func (c *brainClient) OnNewMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := grpc.Invoke(ctx, "/protocols.Brain/OnNewMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Brain service

type BrainServer interface {
	// Posts a message from a frontend
	OnNewMessage(context.Context, *MessageRequest) (*MessageResponse, error)
}

func RegisterBrainServer(s *grpc.Server, srv BrainServer) {
	s.RegisterService(&_Brain_serviceDesc, srv)
}

func _Brain_OnNewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainServer).OnNewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.Brain/OnNewMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainServer).OnNewMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Brain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocols.Brain",
	HandlerType: (*BrainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnNewMessage",
			Handler:    _Brain_OnNewMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "squidbot.proto",
}

func init() { proto.RegisterFile("squidbot.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0x80, 0xdf, 0xb4, 0x6f, 0xab, 0xc6, 0x24, 0x45, 0xf2, 0x64, 0x0a, 0x03, 0x04, 0x21, 0x31,
	0x65, 0x80, 0x85, 0x39, 0x0b, 0x30, 0xd0, 0x86, 0xc0, 0x6e, 0x39, 0xf5, 0xa9, 0x58, 0x4a, 0xce,
	0x69, 0xec, 0x80, 0xf8, 0xa9, 0xfc, 0x1b, 0x9c, 0x0f, 0x15, 0x15, 0x10, 0x4b, 0x2e, 0x7a, 0xee,
	0x49, 0xee, 0x8b, 0xcc, 0xcd, 0xb6, 0x51, 0x32, 0xd7, 0x36, 0xae, 0x6a, 0x6d, 0x35, 0xf5, 0xbb,
	0xb0, 0xd6, 0x85, 0x89, 0x3e, 0x3c, 0x32, 0x7f, 0x00, 0x63, 0xc4, 0x06, 0x32, 0xd8, 0x36, 0x60,
	0x2c, 0x3d, 0x26, 0x7e, 0x83, 0xca, 0xbd, 0x73, 0x25, 0x99, 0x77, 0xea, 0x5d, 0x8e, 0xb3, 0x59,
	0x0f, 0xee, 0x25, 0x3d, 0x21, 0xbe, 0x55, 0xa5, 0xd3, 0x44, 0x59, 0xb1, 0x51, 0x97, 0xfc, 0x02,
	0xf4, 0x9c, 0x84, 0x06, 0x50, 0x42, 0xcd, 0x5f, 0x04, 0xca, 0x02, 0xd8, 0xd8, 0x19, 0x7e, 0x16,
	0xf4, 0xf0, 0xae, 0x63, 0xf4, 0x8c, 0x04, 0x65, 0x5f, 0x91, 0xe7, 0x5a, 0xbe, 0xb3, 0xff, 0x9d,
	0x73, 0x30, 0xb0, 0xc4, 0xa1, 0x56, 0x59, 0xbb, 0x3f, 0x20, 0x14, 0x1c, 0x45, 0x09, 0x6c, 0xd2,
	0x2b, 0x03, 0x5b, 0x3a, 0xe4, 0x94, 0x50, 0x19, 0xae, 0x11, 0xb8, 0xd5, 0x6d, 0x60, 0x53, 0xe7,
	0xcc, 0x32, 0xa2, 0xcc, 0x0a, 0xe1, 0x59, 0xbb, 0x47, 0xf4, 0x48, 0x0e, 0x77, 0xa3, 0x99, 0x4a,
	0xa3, 0x81, 0xbf, 0x67, 0xfb, 0xde, 0xd8, 0xe8, 0x47, 0x63, 0x57, 0x29, 0x99, 0x24, 0xb5, 0x50,
	0x48, 0x6f, 0x49, 0xb0, 0xc2, 0x25, 0xbc, 0x0d, 0x05, 0xe8, 0x51, 0xbc, 0xdb, 0x69, 0xbc, 0xbf,
	0xcf, 0xc5, 0xe2, 0xb7, 0x54, 0xdf, 0x4f, 0xf4, 0x2f, 0xb9, 0x21, 0x17, 0xba, 0xde, 0xc4, 0x42,
	0xbe, 0x02, 0xda, 0xa6, 0x06, 0x77, 0x2a, 0x21, 0xe3, 0xfd, 0x83, 0xb5, 0x9f, 0x26, 0xe1, 0xd3,
	0xc0, 0xd2, 0x16, 0xa5, 0x5e, 0x3e, 0xed, 0x72, 0xd7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x84,
	0x3f, 0x28, 0xe1, 0xde, 0x01, 0x00, 0x00,
}
